# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=96)),
                ('last_name', models.CharField(blank=True, max_length=96)),
                ('email', models.EmailField(blank=True, max_length=96)),
                ('year', models.IntegerField(default=1)),
                ('budget', models.BooleanField(default=True, help_text='Show is student paid for courses. Allows us to calculate price for future')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=96, unique=True)),
                ('teacher', models.CharField(max_length=96)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='subj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Subject'),
        ),
    ]
