# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_faculty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=96, unique=True),
        ),
    ]
