# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161123_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty_id',
            field=models.CharField(choices=[('INFORMATICA', 'INFORMATICA'), ('BIOLOGY', 'BIOLOGY'), ('POLYTOLOGY', 'POLITOLOGY')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
