# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161123_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
